name: DamageIndicator
version: '${version}'
main: org.teenkung123.damageindicator.DamageIndicator
api-version: '1.20'
softdepend:
  - PlaceholderAPI
  - MythicLib
  - Citizens
depend:
  - DecentHolograms